var s = window.document.getElementById('start')
var s1 = Number(s.value)
var e = window.document.getElementById('end')
var e1 = Number(s1.value)
var p = window.document.getElementById('pace')
var p1 = Number(p.value)

console.log(s1)
console.log(e1)
console.log(p1)